### ISSUE TITLE
Functie veel te lang, opsplitsen in functies

### ISSUE THREAD

**Issue by JeroenHeemskerk** [emileykappar/educom-webshop-basis#14]
Betreft [contact.php regel 3-147](https://github.com/emileykappar/educom-webshop-basis/blob/5fad3f2e1026e44a9bd8ba4d60a8fb60e23e3432/contact.php#L3-L147) deze functie is veel te lang, dit zou in meerdere functies moeten worden opgesplitst. 

Ik zou bijvoorbeeld 
* het formulier [regel 71-136](https://github.com/emileykappar/educom-webshop-basis/blob/5fad3f2e1026e44a9bd8ba4d60a8fb60e23e3432/contact.php#L71-L134) onderbrengen in een ```function showContactForm($data)``` waarbij ```$name``` wordt vervangen door ```$data['name']``` etc.
* het bedankje [regel 138-145](https://github.com/emileykappar/educom-webshop-basis/blob/5fad3f2e1026e44a9bd8ba4d60a8fb60e23e3432/contact.php#L138-L145) onderbrengen in een ```function showContactThanks($data)``` waarbij ```$name``` wordt vervangen door ```$data['name']``` etc.
* het deel wat valideerd [regel 5-68](https://github.com/emileykappar/educom-webshop-basis/blob/5fad3f2e1026e44a9bd8ba4d60a8fb60e23e3432/contact.php#L5-L68) onderbrengen in een ```function validateContact($data)``` waarbij onderaan een ```return array("name" => $name, "nameErr" => $nameErr, "gender" => $gender, /* etc. */ "valid" = $valid };``` zodat deze een associatieve array teruggeeft met daarin de velden en errors.
* de showContactContent zou er dan alsvolgt uitzien:
``` 
function showContactContent() {
  $data = validateContact();
  if ($data['valid']) {
    showContactThanks($data);
  } else {
    showContactForm($data);
  }
}
```

**Comment by emileykappar** [comment]
@JeroenHeemskerk Ik heb best wat veranderd maar het was me even ontschoten dat het handiger is om na elke opgeloste issue even te committen. Dit zal ik vanaf nu wel doen voor het overzicht! 

Ook heb ik deze nu alvast gecommit maar voor de login en register pagina's waar ik afgelopen week aan was begonnen, moet ik dit deze feedback nog aanpassen. Ook zie ik dat de ingevulde values niet meer blijven staan wanneer er op submit geklikt wordt: daar ben ik ook mee bezig :)

**Comment by JeroenHeemskerk** [comment]
Dat is goed Emiley, ik kijk er alvast naar.

Het laatste issue wat je meldt heeft te maken met dat je de regel
`$gender = testInput(getPostVar["gender"]);`
VOOR
`if (empty($gender)) `

moet zetten (en dan de 'else' laten vervallen)

**Comment by JeroenHeemskerk** [comment]
Dit issue is natuurlijk ook van toepassing op het login en register form, maar misschien was je daar nog niet aan toegekomen.
