### ISSUE TITLE
04-A: Opdracht 2.1: Ontwerp structuur aanbrengen in de code en routering toevoegen

### ISSUE THREAD

**Issue by JeroenHeemskerk** [emileykappar/educom-webshop-basis#6]
<ul>
<li>We gaan in deze opdracht de code herschikken zodat:<br />
<ul>
<li>alle client requests worden door hetzelfde script afgehandeld. Dit heet "single door routing".</li>
<li>Met een parameter in het GET/POST request wordt aangegeven welke pagina getoond moet worden.
<ul>
<li>Bijvoorbeeld in het menu komt. "&lt;a href="index.php<strong>?page=about</strong>&gt; ABOUT &lt;/a&gt;".</li>
<li>bij POST requests dien je GEEN urlparameter te gebruiken (dus &lt;form action="index.php<s>?page=contact</s>" method="post"&gt;).<br /><br /></li>
</ul>
</li>
</ul>
</li>
<li>Maak een PSD waarbij je ervan uitgaat dat er twee stappen nodig zijn voor de applicatie&nbsp;<br />
<ol>
<li>
<p>Alle aanvragen van de client (browser) worden verstuurd naar het bestand index.php op de server, en er kunnen 2 soorten aanvragen worden gedaan:</p>
<ul>
<li>Een&nbsp;GET request&nbsp;als gevolg van het klikken op een &lt;a&gt;-tag in het menu.In dit geval wordt in de URL meegegeven welke pagina wordt gevraagd.</li>
<li>Een POST request als gevolg van het klikken op een submit-button in een &lt;form&gt;.In dit geval wordt in de POST meegegeven welke pagina er wordt gepost.</li>
</ul>
</li>
<li>De betreffende pagina moet worden getoond, hierbij moeten zaken die gemeenschappelijk zijn zoals Header, Menu en Footer maar op 1 plek voorkomen.</li>
</ol>
</li>
<li>In een PSD zou het top-level er dus alsvolgt uit kunnen zien:<br /><span style="color: #0000ff;">PSD: Top-level</span><br />
<table style="border-collapse: collapse; width: 15.6086%;" border="1">
<tbody>
<tr>
<td style="width: 100%;"><span style="color: #0000ff;">&nbsp;<em><strong>getRequestedPage</strong></em></span></td>
</tr>
<tr>
<td style="width: 100%;"><span style="color: #0000ff;">&nbsp;<em><strong>showResponsePage<br /></strong></em></span></td>
</tr>
</tbody>
</table>
</li>
<li>Werk ieder van deze blokken uit, en als je weer op een <em><strong>complexe stap</strong></em> stuit, werk die stap dan ook weer in een eigen PSD uit, bijv.<br /><span style="color: #0000ff;">PSD: showBodySection</span><br />
<table style="border-collapse: collapse; width: 15.4072%; height: 108px;" border="1">
<tbody>
<tr style="height: 18px;">
<td style="width: 100%; height: 18px;"><span style="color: #0000ff;">&nbsp;showBodyStart</span></td>
</tr>
<tr style="height: 18px;">
<td style="width: 100%; height: 18px;"><span style="color: #0000ff;">&nbsp;showHeader</span></td>
</tr>
<tr style="height: 18px;">
<td style="width: 100%; height: 18px;"><span style="color: #0000ff;">&nbsp;showMenu</span></td>
</tr>
<tr style="height: 18px;">
<td style="width: 100%; height: 18px;"><span style="color: #0000ff;">&nbsp;<em><strong>showContent</strong></em></span></td>
</tr>
<tr style="height: 18px;">
<td style="width: 100%; height: 18px;"><span style="color: #0000ff;">&nbsp;showFooter</span></td>
</tr>
<tr style="height: 18px;">
<td style="width: 100%; height: 18px;"><span style="color: #0000ff;">&nbsp;showBodyEnd</span></td>
</tr>
</tbody>
</table>
</li>
<li>Plaats de PSD in de /PSD folder in je repository
<ul>
<li>Indien je de PSD op papier hebt gemaakt, maak dan een foto en plaats deze in de /PSD folder</li>
<li>Indien je de PSD met draw.io hebt gemaakt, maak hier dan een PNG van en plaats deze in de /PSD folder</li>
<li>Indien je de PSD met een lokale tool hebt gemaakt, maak hier dan een PNG van en plaats deze in de /PSD folder</li>
</ul>
</li>
<li>Commit de PSD naar je lokale repository (o.v.v. het issue nummer).</li>
<li>Push de commit naar GitHub</li>
</ul>

**Comment by emileykappar** [comment]
Hi Jeroen, 

Zou je me op weg kunnen helpen/feedback kunnen geven op de volgende onderdelen uit 2.1 zodra je hier tijd voor hebt?

- De waardes van het dropdown menu voor de gender blijven niet staan 
- De aangeklikte radio button blijft niet staat 
- De isset functie krijg ik niet goed ge-echo't 
- De volledige paginas zijn nog steeds niet helemaal volgensmij. Hoe kan ik dit zelf testen via de browser en waar zou ik dit aan kunnen passen? 

Groetjes Emiley
